### ISSUE TITLE
Документация по подключению домофона через Telegram в HomeAssistant

### ISSUE THREAD

**Issue by strannick-ru** [SCratORS/BlueStreak#23]
Следуйте этим шагам, чтобы с нуля настроить управление домофоном через Telegram.

#### Часть 1: Подготовка в Telegram

**Шаг 1: Создайте бота**

1.  Откройте Telegram и найдите официального бота `@BotFather`.
2.  Напишите ему команду `/newbot`.
3.  Задайте имя для вашего бота, например, "Мой Домофон".
4.  Задайте уникальное имя пользователя (username), которое должно заканчиваться на `bot`, например, `my_home_intercom_bot`.
5.  `@BotFather` пришлет вам сообщение с **API-ключом (токеном)**. Это длинная строка вида `1234567890:ABC-DEF1234ghIkl-zyx57W2v1u1234567890`. **Скопируйте и сохраните его в надежном месте. Он понадобится нам позже.**

**Шаг 2: Создайте групповой чат и получите его ID**

1.  В Telegram создайте новую группу. Добавьте в нее хотя бы одного участника (например, себя из другого аккаунта или любого друга).
2.  Теперь нужно узнать `ID` этой группы. Самый простой способ:
    *   Найдите в поиске бота `@myidbot` и добавьте его в вашу новую группу.
    *   Напишите в группе команду `/getgroupid`.
    *   Бот пришлет в ответ ID группы. Он будет отрицательным, например, `-1002816889873`. **Скопируйте и сохраните этот ID.**
    *   После этого бота `@myidbot` можно удалить из группы.

**Шаг 3: Добавьте вашего бота в чат**

1.  В настройках группы добавьте нового участника. В поиске введите `username` вашего бота (например, `@my_home_intercom_bot`) и добавьте его.
2.  **Критически важно:** Сделайте бота администратором с правом на удаление сообщений.
    *   В настройках группы зайдите в "Администраторы" -> "Добавить администратора".
    *   Выберите вашего бота.
    *   Убедитесь, что у него включена опция **"Удаление сообщений"**. Сохраните изменения.

#### Часть 2: Настройка интеграции в Home Assistant

**Шаг 4: Установите интеграцию Telegram**

1.  В Home Assistant перейдите в **Настройки** -> **Устройства и службы**.
2.  Нажмите кнопку **"Добавить интеграцию"**.
3.  В поиске введите `Telegram` и выберите **"Telegram broadcast"**.

**Шаг 5: Выберите метод подключения (Polling vs Webhook)**

Вам будет предложено два варианта:
*   **Polling (Опрос):** Home Assistant будет периодически (раз в несколько секунд) спрашивать у Telegram: "Есть ли новые сообщения?". Этот метод прост в настройке, не требует доступа к вашему Home Assistant из интернета и надежно работает.
*   **Webhook (Вебхук):** Telegram будет мгновенно отправлять обновления в Home Assistant. Это быстрее и эффективнее, но требует, чтобы ваш Home Assistant был доступен извне по защищенному адресу (HTTPS).

**Рекомендация:** Если вы не уверены, выбирайте **Polling**. Это самый простой и безотказный способ.

**Шаг 6: Настройте интеграцию**

В появившемся окне введите данные, которые мы сохранили ранее:
*   **API Key:** Вставьте сюда токен вашего бота.
*   **Allowed Chat IDs:** Вставьте сюда ID вашей группы (отрицательное число).

Нажмите "Отправить". Если все сделано правильно, интеграция добавится без ошибок.

#### Часть 3: Добавление автоматизации

**Шаг 7: Создайте автоматизацию и вставьте код**

1.  Перейдите в **Настройки** -> **Автоматизации и сцены**.
2.  Нажмите **"Создать автоматизацию"** -> **"Создать новую автоматизацию"**.
3.  В правом верхнем углу нажмите на три точки (`...`) и выберите **"Редактировать в YAML"**.
4.  Полностью сотрите весь текст, который там есть, и вставьте следующий код:

```yaml
id: telegram_intercom_unified
alias: 'Домофон: Уведомление и обработка'
mode: restart
trigger:
  - platform: state
    entity_id: binary_sensor.smartintercom_line_detect
    to: 'on'
condition:
  - condition: state
    entity_id: switch.smartintercom_accept_call
    state: 'off'
  - condition: state
    entity_id: switch.smartintercom_reject_call
    state: 'off'
  - condition: state
    entity_id: select.smartintercom_modes
    state: 'Не активен'
action:
  - service: telegram_bot.send_message
    data:
      message: "📞 Кто-то звонит в домофон. Что сделать?"
      inline_keyboard:
        - "✅ Открыть дверь:/open_door, ❌ Отклонить:/reject_call"
    response_variable: sent_message
  - wait_for_trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          message:
            message_id: '{{ sent_message.chats[0].message_id }}'
          chat_id: '{{ sent_message.chats[0].chat_id }}'
    timeout: 60
    continue_on_timeout: true
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger is not none }}"
          - condition: state
            entity_id: binary_sensor.smartintercom_line_detect
            state: 'on'
        sequence:
          - choose:
              - conditions:
                  - "{{ wait.trigger.event.data.data == '/open_door' }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: switch.smartintercom_accept_call
              - conditions:
                  - "{{ wait.trigger.event.data.data == '/reject_call' }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: switch.smartintercom_reject_call
          - service: telegram_bot.answer_callback_query
            data:
              callback_query_id: '{{ wait.trigger.event.data.id }}'
              message: "✅ Готово!"
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger is not none }}"
        sequence:
          - service: telegram_bot.answer_callback_query
            data:
              callback_query_id: '{{ wait.trigger.event.data.id }}'
              message: "Уже не актуально. Звонок завершен."
              show_alert: true
  - service: telegram_bot.delete_message
    data:
      chat_id: '{{ sent_message.chats[0].chat_id }}'
      message_id: '{{ sent_message.chats[0].message_id }}'
```

**Шаг 8: Адаптируйте код под вашу систему**

Это **самый важный шаг**. В коде выше используются шаблонные имена сущностей. Вам нужно заменить их на те, которые создала ваша интеграция домофона.

Найдите в коде и замените следующие `entity_id`:
*   `binary_sensor.smartintercom_line_detect`
*   `switch.smartintercom_accept_call`
*   `switch.smartintercom_reject_call`
*   `select.smartintercom_modes`

Свои реальные ID можно найти в **Инструменты разработчика -> Состояния**.

**Шаг 9: Сохраните и проверьте**

Нажмите кнопку "Сохранить". Теперь ваша автоматизация готова. Позвоните в домофон, чтобы проверить ее работу
